name: Demo Workflow
on:
  push:

jobs:
  build-car:
    runs-on: ubuntu-latest
    steps:
      - name: Build the car
        run: |
          mkdir -p build
          cd build
          touch car.txt
          echo "chassis" >> car.txt
          echo "engine" >> car.txt
          echo "wheels" >> car.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: car
          path: build/car.txt

  test-the-car:
    runs-on: ubuntu-latest
    needs: build-car    # ensures correct order (dependency)

    steps:
      - name: Download car artifact
        uses: actions/download-artifact@v4
        with:
          name: car

      - name: Test the car
        run: |
          test -f car.txt
          grep "chassis" car.txt
          grep "engine" car.txt
          grep "wheels" car.txt
