name: Demo Workflow
on: push
jobs:
  build-and-test-car:
    runs-on: ubuntu-latest
    steps:
      - name: Build the car
        run: |
          mkdir build
          cd build
          touch car.txt
          echo "chassis" >> car.txt
          echo "engine" >> car.txt
          echo "wheels" >> car.txt
      
      - name: Test the car
        run: |
          test -f build/car.txt
          cd build
          grep "chassis" car.txt
          grep "engine" car.txt
          grep "wheels" car.txt
